version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: illuminate-postgres
    environment:
      POSTGRES_DB: illuminate_db
      POSTGRES_USER: illuminate
      POSTGRES_PASSWORD: illuminate123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d/migrations
    networks:
      - illuminate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U illuminate -d illuminate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (Optional - for caching)
  redis:
    image: redis:7-alpine
    container_name: illuminate-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - illuminate-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: illuminate-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@illuminate.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - illuminate-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  illuminate-network:
    driver: bridge
