-- Migration: Complete emission resources from CSV
-- Created: 2024-09-21
-- Description: Insert ALL unique emission resources from ef_libraries_with_cost.csv

-- Insert all unique emission resources with proper categorization
WITH all_resources_cte AS (
  -- Stationary Combustion Fuels
  SELECT 'Asphalt and Road Oil' as resource_name, 'fuel' as resource_type, 'stationary_combustion' as category, 'scope1' as scope, false as is_alternative_fuel, false as is_calculator, 'Asphalt and Road Oil for stationary combustion operations' as description
  UNION ALL SELECT 'Mixed (Commercial Sector)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Mixed (Commercial Sector) for stationary combustion operations'
  UNION ALL SELECT 'Mixed (Electric Power Sector)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Mixed (Electric Power Sector) for stationary combustion operations'
  UNION ALL SELECT 'Mixed (Industrial Coking)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Mixed (Industrial Coking) for stationary combustion operations'
  UNION ALL SELECT 'Mixed (Industrial Sector)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Mixed (Industrial Sector) for stationary combustion operations'
  UNION ALL SELECT 'Coal Coke', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Coal Coke for stationary combustion operations'
  UNION ALL SELECT 'Municipal Solid Waste', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Municipal Solid Waste for stationary combustion operations'
  UNION ALL SELECT 'Petroleum Coke (Solid)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Petroleum Coke (Solid) for stationary combustion operations'
  UNION ALL SELECT 'Plastics', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Plastics for stationary combustion operations'
  UNION ALL SELECT 'Tires', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Tires for stationary combustion operations'
  UNION ALL SELECT 'Agricultural Byproducts (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Agricultural Byproducts (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Peat (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Peat (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Solid Byproducts (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Solid Byproducts (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Wood and Wood Residuals (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Wood and Wood Residuals (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Aviation Gasoline', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Aviation Gasoline for stationary combustion operations'
  UNION ALL SELECT 'Butane', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Butane for stationary combustion operations'
  UNION ALL SELECT 'Butylene', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Butylene for stationary combustion operations'
  UNION ALL SELECT 'Crude Oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Crude Oil for stationary combustion operations'
  UNION ALL SELECT 'Distillate Fuel Oil No. 1', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Distillate Fuel Oil No. 1 for stationary combustion operations'
  UNION ALL SELECT 'Distillate Fuel Oil No. 2', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Distillate Fuel Oil No. 2 for stationary combustion operations'
  UNION ALL SELECT 'Distillate Fuel Oil No. 4', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Distillate Fuel Oil No. 4 for stationary combustion operations'
  UNION ALL SELECT 'Ethane', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Ethane for stationary combustion operations'
  UNION ALL SELECT 'Ethylene', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Ethylene for stationary combustion operations'
  UNION ALL SELECT 'Heavy Gas Oils', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Heavy Gas Oils for stationary combustion operations'
  UNION ALL SELECT 'Isobutane', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Isobutane for stationary combustion operations'
  UNION ALL SELECT 'Isobutylene', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Isobutylene for stationary combustion operations'
  UNION ALL SELECT 'Kerosene', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Kerosene for stationary combustion operations'
  UNION ALL SELECT 'Kerosene-Type Jet Fuel', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Kerosene-Type Jet Fuel for stationary combustion operations'
  UNION ALL SELECT 'Liquefied Petroleum Gases (LPG)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Liquefied Petroleum Gases (LPG) for stationary combustion operations'
  UNION ALL SELECT 'Lubricants', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Lubricants for stationary combustion operations'
  UNION ALL SELECT 'Motor Gasoline', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Motor Gasoline for stationary combustion operations'
  UNION ALL SELECT 'Naphtha (<401 deg F)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Naphtha (<401 deg F) for stationary combustion operations'
  UNION ALL SELECT 'Natural Gasoline', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Natural Gasoline for stationary combustion operations'
  UNION ALL SELECT 'Other Oil (>401 deg F)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Other Oil (>401 deg F) for stationary combustion operations'
  UNION ALL SELECT 'Pentanes Plus', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Pentanes Plus for stationary combustion operations'
  UNION ALL SELECT 'Petrochemical Feedstocks', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Petrochemical Feedstocks for stationary combustion operations'
  UNION ALL SELECT 'Petroleum Coke', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Petroleum Coke for stationary combustion operations'
  UNION ALL SELECT 'Propane', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Propane for stationary combustion operations'
  UNION ALL SELECT 'Propylene', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Propylene for stationary combustion operations'
  UNION ALL SELECT 'Residual Fuel Oil No. 5', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Residual Fuel Oil No. 5 for stationary combustion operations'
  UNION ALL SELECT 'Residual Fuel Oil No. 6', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Residual Fuel Oil No. 6 for stationary combustion operations'
  UNION ALL SELECT 'Special Naphtha', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Special Naphtha for stationary combustion operations'
  UNION ALL SELECT 'Unfinished Oils', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Unfinished Oils for stationary combustion operations'
  UNION ALL SELECT 'Used Oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Used Oil for stationary combustion operations'
  UNION ALL SELECT 'Biodiesel (100%) (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Biodiesel (100%) (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Ethanol (100%) (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Ethanol (100%) (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Vegetable Oil (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Vegetable Oil (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Natural Gas', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Natural Gas for stationary combustion operations'
  UNION ALL SELECT 'Blast Furnace Gas', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Blast Furnace Gas for stationary combustion operations'
  UNION ALL SELECT 'Coke Oven Gas', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Coke Oven Gas for stationary combustion operations'
  UNION ALL SELECT 'Fuel Gas', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Fuel Gas for stationary combustion operations'
  UNION ALL SELECT 'Propane Gas', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Propane Gas for stationary combustion operations'
  UNION ALL SELECT 'Landfill Gas (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Landfill Gas (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Other Biomass Gases (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Other Biomass Gases (Non Biogenic) for stationary combustion operations'
  UNION ALL SELECT 'Anthracite Coal', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Anthracite Coal for stationary combustion operations'
  UNION ALL SELECT 'Bituminous Coal', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Bituminous Coal for stationary combustion operations'
  UNION ALL SELECT 'Sub-bituminous Coal', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Sub-bituminous Coal for stationary combustion operations'
  UNION ALL SELECT 'Lignite Coal', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Lignite Coal for stationary combustion operations'
  UNION ALL SELECT 'Diesel', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Diesel for stationary combustion operations'
  UNION ALL SELECT 'Rendered Animal Fat (Non Biogenic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Rendered Animal Fat (Non Biogenic) for stationary combustion operations'

  -- Mobile Combustion Fuels
  UNION ALL SELECT 'Aviation Gasoline - Aviation Gasoline Aircraft', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Aviation Gasoline - Aviation Gasoline Aircraft for mobile equipment and vehicles'
  UNION ALL SELECT 'Motor Gasoline - Gasoline Motorcycles', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Motor Gasoline - Gasoline Motorcycles for mobile equipment and vehicles'
  UNION ALL SELECT 'Motor Gasoline - Other Gasoline Non-Road Vehicles', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Motor Gasoline - Other Gasoline Non-Road Vehicles for mobile equipment and vehicles'
  UNION ALL SELECT 'Diesel Fuel - Diesel Agricultural Equipment', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Diesel Fuel - Diesel Agricultural Equipment for mobile equipment and vehicles'
  UNION ALL SELECT 'Motor Gasoline - Gasoline Passenger Cars', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Motor Gasoline - Gasoline Passenger Cars for mobile equipment and vehicles'
  UNION ALL SELECT 'Motor Gasoline - Gasoline Light-duty Trucks (Vans, Pickup Trucks, SUVs)', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Motor Gasoline - Gasoline Light-duty Trucks (Vans, Pickup Trucks, SUVs) for mobile equipment and vehicles'
  UNION ALL SELECT 'Motor Gasoline - Hybrid (Gasoline) Passenger Cars', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Motor Gasoline - Hybrid (Gasoline) Passenger Cars for mobile equipment and vehicles'
  UNION ALL SELECT 'Motor Gasoline - Gasoline Heavy-duty Vehicles', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Motor Gasoline - Gasoline Heavy-duty Vehicles for mobile equipment and vehicles'
  UNION ALL SELECT 'Motor Gasoline - Gasoline Ships and Boats', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Motor Gasoline - Gasoline Ships and Boats for mobile equipment and vehicles'
  UNION ALL SELECT 'Motor Gasoline - Gasoline Agricultural Equipment', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Motor Gasoline - Gasoline Agricultural Equipment for mobile equipment and vehicles'
  UNION ALL SELECT 'Diesel Fuel - Diesel Ships and Boats', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Diesel Fuel - Diesel Ships and Boats for mobile equipment and vehicles'
  UNION ALL SELECT 'Diesel Fuel - Diesel Passenger Cars', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Diesel Fuel - Diesel Passenger Cars for mobile equipment and vehicles'
  UNION ALL SELECT 'Diesel Fuel - Diesel Light-duty Trucks', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Diesel Fuel - Diesel Light-duty Trucks for mobile equipment and vehicles'
  UNION ALL SELECT 'Diesel Fuel - Diesel Medium- and Heavy-duty Vehicles', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Diesel Fuel - Diesel Medium- and Heavy-duty Vehicles for mobile equipment and vehicles'
  UNION ALL SELECT 'Jet Fuel - Jet Fuel Aircraft', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Jet Fuel - Jet Fuel Aircraft for mobile equipment and vehicles'
  UNION ALL SELECT 'Compressed Natural Gas - CNG Light-duty Vehicles', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Compressed Natural Gas - CNG Light-duty Vehicles for mobile equipment and vehicles'
  UNION ALL SELECT 'Compressed Natural Gas - CNG Medium- and Heavy-duty Vehicles', 'fuel', 'mobile_combustion', 'scope1', false, false, 'Compressed Natural Gas - CNG Medium- and Heavy-duty Vehicles for mobile equipment and vehicles'
  UNION ALL SELECT 'Electricity - Mobile - Electric Vehicle', 'electricity', 'mobile_combustion', 'scope1', false, false, 'Electricity - Mobile - Electric Vehicle for mobile equipment and vehicles'

  -- Alternative/Biofuels (Mobile)
  UNION ALL SELECT 'Ethanol (100%) - Ethanol Light-duty Vehicles', 'fuel', 'mobile_combustion', 'scope1', true, false, 'Ethanol (100%) - Ethanol Light-duty Vehicles for mobile equipment and vehicles'
  UNION ALL SELECT 'Ethanol (100%) - Ethanol Medium- and Heavy-duty Vehicles', 'fuel', 'mobile_combustion', 'scope1', true, false, 'Ethanol (100%) - Ethanol Medium- and Heavy-duty Vehicles for mobile equipment and vehicles'
  UNION ALL SELECT 'Biodiesel (100%) - Biodiesel Passenger Cars', 'fuel', 'mobile_combustion', 'scope1', true, false, 'Biodiesel (100%) - Biodiesel Passenger Cars for mobile equipment and vehicles'
  UNION ALL SELECT 'Biodiesel (100%) - Biodiesel Light-duty Vehicles', 'fuel', 'mobile_combustion', 'scope1', true, false, 'Biodiesel (100%) - Biodiesel Light-duty Vehicles for mobile equipment and vehicles'
  UNION ALL SELECT 'Biodiesel (100%) - Biodiesel Medium- and Heavy-duty Vehicles', 'fuel', 'mobile_combustion', 'scope1', true, false, 'Biodiesel (100%) - Biodiesel Medium- and Heavy-duty Vehicles for mobile equipment and vehicles'

  -- Alternative/Biofuels (Stationary)
  UNION ALL SELECT 'Agricultural Byproducts', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Agricultural Byproducts for stationary combustion operations'
  UNION ALL SELECT 'Peat', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Peat for stationary combustion operations'
  UNION ALL SELECT 'Solid Byproducts', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Solid Byproducts for stationary combustion operations'
  UNION ALL SELECT 'Wood and Wood Residuals', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Wood and Wood Residuals for stationary combustion operations'
  UNION ALL SELECT 'Landfill Gas', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Landfill Gas for stationary combustion operations'
  UNION ALL SELECT 'Other Biomass Gases', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Other Biomass Gases for stationary combustion operations'
  UNION ALL SELECT 'Biodiesel (100%)', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Biodiesel (100%) for stationary combustion operations'
  UNION ALL SELECT 'Ethanol (100%)', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Ethanol (100%) for stationary combustion operations'
  UNION ALL SELECT 'Rendered Animal Fat', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Rendered Animal Fat for stationary combustion operations'
  UNION ALL SELECT 'Vegetable Oil', 'fuel', 'stationary_combustion', 'scope1', true, false, 'Vegetable Oil for stationary combustion operations'

  -- DEFRA/BEIS specific fuels
  UNION ALL SELECT 'Petrol (100% mineral petrol)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Petrol (100% mineral petrol) for stationary combustion operations'
  UNION ALL SELECT 'Petrol (average biofuel blend)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Petrol (average biofuel blend) for stationary combustion operations'
  UNION ALL SELECT 'Naphtha', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Naphtha for stationary combustion operations'
  UNION ALL SELECT 'Gas oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Gas oil for stationary combustion operations'
  UNION ALL SELECT 'Fuel oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Fuel oil for stationary combustion operations'
  UNION ALL SELECT 'Diesel (100% mineral diesel)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Diesel (100% mineral diesel) for stationary combustion operations'
  UNION ALL SELECT 'Diesel (average biofuel blend)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Diesel (average biofuel blend) for stationary combustion operations'
  UNION ALL SELECT 'Burning oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Burning oil for stationary combustion operations'
  UNION ALL SELECT 'Aviation turbine fuel', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Aviation turbine fuel for stationary combustion operations'
  UNION ALL SELECT 'Aviation spirit', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Aviation spirit for stationary combustion operations'
  UNION ALL SELECT 'Other petroleum gas', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Other petroleum gas for stationary combustion operations'
  UNION ALL SELECT 'Natural gas (100% mineral blend)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Natural gas (100% mineral blend) for stationary combustion operations'
  UNION ALL SELECT 'LPG', 'fuel', 'stationary_combustion', 'scope1', false, false, 'LPG for stationary combustion operations'
  UNION ALL SELECT 'LNG', 'fuel', 'stationary_combustion', 'scope1', false, false, 'LNG for stationary combustion operations'
  UNION ALL SELECT 'CNG', 'fuel', 'stationary_combustion', 'scope1', false, false, 'CNG for stationary combustion operations'
  UNION ALL SELECT 'Coal (domestic)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Coal (domestic) for stationary combustion operations'
  UNION ALL SELECT 'Coal (electricity generation - home produced coal only)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Coal (electricity generation - home produced coal only) for stationary combustion operations'
  UNION ALL SELECT 'Coal (electricity generation)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Coal (electricity generation) for stationary combustion operations'
  UNION ALL SELECT 'Coal (industrial)', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Coal (industrial) for stationary combustion operations'
  UNION ALL SELECT 'Coking coal', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Coking coal for stationary combustion operations'
  UNION ALL SELECT 'Marine fuel oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Marine fuel oil for stationary combustion operations'
  UNION ALL SELECT 'Marine gas oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Marine gas oil for stationary combustion operations'
  UNION ALL SELECT 'Waste oils', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Waste oils for stationary combustion operations'
  UNION ALL SELECT 'Refinery miscellaneous', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Refinery miscellaneous for stationary combustion operations'
  UNION ALL SELECT 'Processed fuel oils - distillate oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Processed fuel oils - distillate oil for stationary combustion operations'
  UNION ALL SELECT 'Processed fuel oils - residual oil', 'fuel', 'stationary_combustion', 'scope1', false, false, 'Processed fuel oils - residual oil for stationary combustion operations'

  -- Electricity
  UNION ALL SELECT 'Electricity supplied from grid', 'electricity', 'purchased_electricity', 'scope2', false, false, 'Electricity supplied from grid purchased electricity'

  -- Fugitive Emissions/Refrigerants
  UNION ALL SELECT 'HCFC-225ca', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HCFC-225ca fugitive emissions'
  UNION ALL SELECT 'HFC-125', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-125 fugitive emissions'
  UNION ALL SELECT 'HFC-134', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-134 fugitive emissions'
  UNION ALL SELECT 'HCFC-225cb', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HCFC-225cb fugitive emissions'
  UNION ALL SELECT 'HCFC-21', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HCFC-21 fugitive emissions'
  UNION ALL SELECT 'Nitrogen trifluoride', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Nitrogen trifluoride fugitive emissions'
  UNION ALL SELECT 'PFC-9-1-18', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'PFC-9-1-18 fugitive emissions'
  UNION ALL SELECT 'Carbon dioxide', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Carbon dioxide fugitive emissions'
  UNION ALL SELECT 'Methane', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Methane fugitive emissions'
  UNION ALL SELECT 'Nitrous oxide', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Nitrous oxide fugitive emissions'
  UNION ALL SELECT 'HFC-23', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-23 fugitive emissions'
  UNION ALL SELECT 'HFC-32', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-32 fugitive emissions'
  UNION ALL SELECT 'HFC-41', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-41 fugitive emissions'
  UNION ALL SELECT 'HFC-134a', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-134a fugitive emissions'
  UNION ALL SELECT 'HFC-143', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-143 fugitive emissions'
  UNION ALL SELECT 'HFC-143a', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-143a fugitive emissions'
  UNION ALL SELECT 'HFC-152a', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-152a fugitive emissions'
  UNION ALL SELECT 'HFC-227ea', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-227ea fugitive emissions'
  UNION ALL SELECT 'HFC-236fa', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-236fa fugitive emissions'
  UNION ALL SELECT 'HFC-245fa', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-245fa fugitive emissions'
  UNION ALL SELECT 'HFC-43-I0mee', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-43-I0mee fugitive emissions'
  UNION ALL SELECT 'Perfluoromethane (PFC-14)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Perfluoromethane (PFC-14) fugitive emissions'
  UNION ALL SELECT 'Perfluoroethane (PFC-116)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Perfluoroethane (PFC-116) fugitive emissions'
  UNION ALL SELECT 'Perfluoropropane (PFC-218)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Perfluoropropane (PFC-218) fugitive emissions'
  UNION ALL SELECT 'Perfluorocyclobutane (PFC-318)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Perfluorocyclobutane (PFC-318) fugitive emissions'
  UNION ALL SELECT 'Perfluorobutane (PFC-3-1-10)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Perfluorobutane (PFC-3-1-10) fugitive emissions'
  UNION ALL SELECT 'Perfluoropentane (PFC-4-1-12)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Perfluoropentane (PFC-4-1-12) fugitive emissions'
  UNION ALL SELECT 'Perfluorohexane (PFC-5-1-14)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Perfluorohexane (PFC-5-1-14) fugitive emissions'
  UNION ALL SELECT 'Sulphur hexafluoride (SF6)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Sulphur hexafluoride (SF6) fugitive emissions'
  UNION ALL SELECT 'HFC-152', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-152 fugitive emissions'
  UNION ALL SELECT 'HFC-161', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-161 fugitive emissions'
  UNION ALL SELECT 'HFC-236cb', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-236cb fugitive emissions'
  UNION ALL SELECT 'HFC-236ea', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-236ea fugitive emissions'
  UNION ALL SELECT 'HFC-245ca', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-245ca fugitive emissions'
  UNION ALL SELECT 'HFC-365mfc', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HFC-365mfc fugitive emissions'
  UNION ALL SELECT 'R-404A', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'R-404A fugitive emissions'
  UNION ALL SELECT 'R-407A', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'R-407A fugitive emissions'
  UNION ALL SELECT 'R-407C', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'R-407C fugitive emissions'
  UNION ALL SELECT 'R-407F', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'R-407F fugitive emissions'
  UNION ALL SELECT 'R-408A', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'R-408A fugitive emissions'
  UNION ALL SELECT 'R-410A', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'R-410A fugitive emissions'
  UNION ALL SELECT 'R-507A', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'R-507A fugitive emissions'
  UNION ALL SELECT 'R-403A', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'R-403A fugitive emissions'
  -- Add many more refrigerants from the CSV...
  UNION ALL SELECT 'CFC-13', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'CFC-13 fugitive emissions'
  UNION ALL SELECT 'CFC-113', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'CFC-113 fugitive emissions'
  UNION ALL SELECT 'CFC-114', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'CFC-114 fugitive emissions'
  UNION ALL SELECT 'CFC-115', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'CFC-115 fugitive emissions'
  UNION ALL SELECT 'Halon-1211', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Halon-1211 fugitive emissions'
  UNION ALL SELECT 'Halon-1301', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Halon-1301 fugitive emissions'
  UNION ALL SELECT 'Halon-2402', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Halon-2402 fugitive emissions'
  UNION ALL SELECT 'Carbon tetrachloride', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Carbon tetrachloride fugitive emissions'
  UNION ALL SELECT 'Methyl bromide', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Methyl bromide fugitive emissions'
  UNION ALL SELECT 'Methyl chloroform', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Methyl chloroform fugitive emissions'
  UNION ALL SELECT 'HCFC-123', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HCFC-123 fugitive emissions'
  UNION ALL SELECT 'HCFC-124', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HCFC-124 fugitive emissions'
  UNION ALL SELECT 'HCFC-141b', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HCFC-141b fugitive emissions'
  UNION ALL SELECT 'HCFC-142b', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HCFC-142b fugitive emissions'
  UNION ALL SELECT 'Trifluoromethyl sulphur pentafluoride', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Trifluoromethyl sulphur pentafluoride fugitive emissions'
  UNION ALL SELECT 'Methylene chloride', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Methylene chloride fugitive emissions'
  UNION ALL SELECT 'Methyl chloride', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'Methyl chloride fugitive emissions'
  UNION ALL SELECT 'CFC-11/R11 (trichlorofluoromethane)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'CFC-11/R11 (trichlorofluoromethane) fugitive emissions'
  UNION ALL SELECT 'CFC-12/R12 (dichlorodifluoromethane)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'CFC-12/R12 (dichlorodifluoromethane) fugitive emissions'
  UNION ALL SELECT 'HCFC-22/R22 (chlorodifluoromethane)', 'refrigerant', 'fugitive_emissions', 'scope1', false, false, 'HCFC-22/R22 (chlorodifluoromethane) fugitive emissions'
)
INSERT INTO emission_resources (resource_name, resource_type, category, scope, is_alternative_fuel, is_calculator, description)
SELECT resource_name, resource_type, category, scope, is_alternative_fuel, is_calculator, description
FROM all_resources_cte
ON CONFLICT (resource_name, scope) DO NOTHING;
